id: I91776E91
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-05T20:01:44.485411'
last_modified: '2022-06-05T20:01:44.485416'
parser: null
source_metadata:
  title: Shikpo Lingpa Series
  language: bo
  description: 'Texts by the treasure revealer Shikpo Lingpa Gargyi Wangchuk Tsal
    (zhig po gling pa gar gyi dbang phyug rtsal, 1524–1583):'
  volume:
    f5A0F:
      title: 'The Sādhana of the Five Self-Arisen Noble Brothers: An Instruction in
        the Union of Generation and Completion'
      base_file: f5A0F.txt
      order: 1
      parent: Sādhanas
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
